-- Migration: add_ai_generation_job_system
-- Generated by Prisma, applied manually (shadow DB not available)

BEGIN;

-- CreateEnums
CREATE TYPE "pm"."AiMessageExecutionStatus" AS ENUM ('COMPLETED', 'QUEUED', 'PROCESSING', 'FAILED', 'CANCELLED');
CREATE TYPE "pm"."BackgroundJobType" AS ENUM ('IMAGE_GENERATE', 'DOCUMENT_INDEX', 'TEXT_SUMMARY');
CREATE TYPE "pm"."BackgroundJobStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE "pm"."JobOutputStatus" AS ENUM ('PENDING', 'GENERATING', 'COMPLETED', 'FAILED');
CREATE TYPE "pm"."AiAttachmentType" AS ENUM ('IMAGE', 'FILE');
CREATE TYPE "pm"."AiFileStorageType" AS ENUM ('DATABASE', 'OBJECT_STORAGE');

-- AlterTable: add nullable columns to AiChatMessage first
ALTER TABLE "pm"."AiChatMessage" ADD COLUMN "errorMessage" TEXT;
ALTER TABLE "pm"."AiChatMessage" ADD COLUMN "executionStatus" "pm"."AiMessageExecutionStatus";
ALTER TABLE "pm"."AiChatMessage" ADD COLUMN "updatedAt" TIMESTAMP(3);

-- Fill in default values for existing rows
UPDATE "pm"."AiChatMessage" SET "executionStatus" = 'COMPLETED' WHERE "executionStatus" IS NULL;
UPDATE "pm"."AiChatMessage" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;

-- Now enforce NOT NULL
ALTER TABLE "pm"."AiChatMessage" ALTER COLUMN "executionStatus" SET NOT NULL;
ALTER TABLE "pm"."AiChatMessage" ALTER COLUMN "executionStatus" SET DEFAULT 'COMPLETED';
ALTER TABLE "pm"."AiChatMessage" ALTER COLUMN "updatedAt" SET NOT NULL;

-- CreateTable: BackgroundJob
CREATE TABLE "pm"."BackgroundJob" (
    "id" TEXT NOT NULL,
    "type" "pm"."BackgroundJobType" NOT NULL,
    "status" "pm"."BackgroundJobStatus" NOT NULL DEFAULT 'PENDING',
    "payload" JSONB NOT NULL,
    "result" JSONB,
    "errorMessage" TEXT,
    "correlationId" TEXT,
    "traceId" TEXT,
    "parentJobId" TEXT,
    "priority" INTEGER NOT NULL DEFAULT 10,
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "nextRetryAt" TIMESTAMP(3),
    "lockedBy" TEXT,
    "leaseExpiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BackgroundJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable: JobOutput
CREATE TABLE "pm"."JobOutput" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "status" "pm"."JobOutputStatus" NOT NULL DEFAULT 'PENDING',
    "fileAssetId" TEXT,
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "JobOutput_pkey" PRIMARY KEY ("id")
);

-- CreateTable: AiMessageAttachment
CREATE TABLE "pm"."AiMessageAttachment" (
    "id" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,
    "fileAssetId" TEXT NOT NULL,
    "jobOutputId" TEXT,
    "type" "pm"."AiAttachmentType" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AiMessageAttachment_pkey" PRIMARY KEY ("id")
);

-- CreateTable: AiFileAsset
CREATE TABLE "pm"."AiFileAsset" (
    "id" TEXT NOT NULL,
    "storageType" "pm"."AiFileStorageType" NOT NULL DEFAULT 'DATABASE',
    "storageKey" TEXT,
    "checksum" TEXT,
    "size" INTEGER,
    "mimeType" TEXT,
    "bytes" BYTEA,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AiFileAsset_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BackgroundJob_status_priority_createdAt_idx" ON "pm"."BackgroundJob"("status", "priority", "createdAt");
CREATE INDEX "BackgroundJob_correlationId_idx" ON "pm"."BackgroundJob"("correlationId");
CREATE INDEX "BackgroundJob_traceId_idx" ON "pm"."BackgroundJob"("traceId");
CREATE INDEX "JobOutput_jobId_idx" ON "pm"."JobOutput"("jobId");
CREATE UNIQUE INDEX "JobOutput_jobId_sequence_key" ON "pm"."JobOutput"("jobId", "sequence");
CREATE UNIQUE INDEX "AiMessageAttachment_jobOutputId_key" ON "pm"."AiMessageAttachment"("jobOutputId");
CREATE INDEX "AiMessageAttachment_messageId_idx" ON "pm"."AiMessageAttachment"("messageId");
CREATE INDEX "AiMessageAttachment_fileAssetId_idx" ON "pm"."AiMessageAttachment"("fileAssetId");
CREATE INDEX "AiFileAsset_storageKey_idx" ON "pm"."AiFileAsset"("storageKey");
CREATE INDEX "AiFileAsset_checksum_idx" ON "pm"."AiFileAsset"("checksum");

-- AddForeignKey: JobOutput → AiFileAsset
ALTER TABLE "pm"."JobOutput" ADD CONSTRAINT "JobOutput_fileAssetId_fkey"
    FOREIGN KEY ("fileAssetId") REFERENCES "pm"."AiFileAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey: AiMessageAttachment → AiChatMessage
ALTER TABLE "pm"."AiMessageAttachment" ADD CONSTRAINT "AiMessageAttachment_messageId_fkey"
    FOREIGN KEY ("messageId") REFERENCES "pm"."AiChatMessage"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: AiMessageAttachment → AiFileAsset
ALTER TABLE "pm"."AiMessageAttachment" ADD CONSTRAINT "AiMessageAttachment_fileAssetId_fkey"
    FOREIGN KEY ("fileAssetId") REFERENCES "pm"."AiFileAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
